# Generated by Django 6.0.6 on 2026-06-24 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Electronics', 'Electronics'), ('Furniture', 'Furniture'), ('Fashion', 'Fashion'), ('Vehicles', 'Vehicles'), ('Home Goods', 'Home Goods'), ('Sports', 'Sports'), ('Other', 'Other')], max_length=100)),
                ('quoted_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_price', models.DecimalField(decimal_places=2, help_text='Minimum price seller is willing to accept (hidden from buyer)', max_digits=10)),
                ('seller_strategy', models.CharField(choices=[('diplomat', 'The Diplomat (Win-win, cooperative)'), ('shark', 'The Shark (Aggressive, stubborn)'), ('frugal', 'The Frugal (Value-oriented, critical)')], default='diplomat', max_length=50)),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('sold', 'Sold')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Negotiation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_max_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buyer_strategy', models.CharField(choices=[('diplomat', 'The Diplomat (Win-win, cooperative)'), ('shark', 'The Shark (Aggressive, stubborn)'), ('frugal', 'The Frugal (Value-oriented, critical)')], default='diplomat', max_length=50)),
                ('status', models.CharField(choices=[('negotiating', 'Negotiating'), ('agreed', 'Agreed'), ('failed', 'Failed')], default='negotiating', max_length=20)),
                ('agreed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_negotiations', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiations', to='api.item')),
            ],
        ),
        migrations.CreateModel(
            name='NegotiationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('buyer_agent', 'Buyer Agent'), ('seller_agent', 'Seller Agent'), ('system', 'System Event')], max_length=20)),
                ('content', models.TextField()),
                ('price_offered', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('negotiation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.negotiation')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
